@isTest
private class MaintenanceRequestTriggerTest
{
    // everything was created correctly, including the relationships to the vehicle and equipment and the due date
    @isTest static void testMaintenanceRequestsCorrectlyCreated()
    {

    }

    //no work requests were created
    @isTest static void b()
    {

    }

    @isTest static void c()
    {

    }

    @isTest static void d()
    {

    }

}